### PR TITLE
Feature/slim-templates

### PR DESCRIPTION
**Pull request by franckdelage**
Hi @nickjj, I propose this feature, which is adding a **slim** template.
It adds slim-rails gem, and changes the default views to slim-html ones.
Whatever you decide, thank's for all your work :)

### CODE REVIEW

**Comment by russdavisdotcom** [comment]
I'm a slim fan, so I end up installing slim-rails and converting everything to slim. I think this is a great addition. It may add to the first-timer learning curve, but will speed overall development time.

**Comment by nickjj** [comment]
I'm not sure how I managed to miss this PR. Thanks @franckdelage.

Before this is considered to be merged I think we need to discuss how multiple templates could work in orats because `AVAILABLE_TEMPLATES` doesn't necessarily mean template language engines.

For example, what happens if a new orats version comes out where user authentication is a new template choice. Now we need both an erb and slim version of that new authentication template.

**Comment by franckdelage** [comment]
Ah yes, you are right. I didn't saw it this way. 

Well, given it is so easy to convert erb to slim with the dedicated gem, maybe this pull request is not a good idea.

**Comment by nickjj** [comment]
Fair enough. I personally don't use slim but using it involves installing a slim related gem and running a command, that seems like an ok'ish solution for people who use slim.

You're also more than welcome to maintain a slim enabled fork. I could link to it in the README, and once / if nice pattern emerge for making it work we could merge it here.

**Pull request closed without merging**
