### PR TITLE
Bump Ruby version used by Rubocop to 2.5

### PR DESCRIPTION
**Pull request by Quintasan**
Fix #45 failing in Travis CI

### CODE REVIEW

**Comment by Quintasan** [comment]
@nickjj This is optional but I think we could just bump it all the way up to 2.5

**Comment by nickjj** [comment]
I vaguely remember trying 2.5 but ran into a bunch of rubocop warnings. Have you tried running rubocop locally with that setting?

**Comment by Quintasan** [comment]
@nickjj 100% of those is `Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.`

I think it's better to apply this style guide now but it's up to you.

**Comment by nickjj** [comment]
I think we should remove the literal string spam on all of the files, that just feels messy to maintain.

I wonder if rubocop has a way to ignore that at the yml level. I don't think it did at the time I looked.

**Comment by Quintasan** [comment]
@nickjj There you go

**Comment by nickjj** [comment]
Thanks.

**Pull request merged**
